<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net35</TargetFramework>

        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>

        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\..\src\CADShared\Basal\CLS\Volatile.cs" Link="Volatile.cs" />
    </ItemGroup>

</Project>