<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x86</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="GlobalUsings.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="..\..\src\CADShared\PE\*.cs" Link="PE\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <SharedProjectReference Include="..\..\src\CADShared\CADShared.shproj" />
  </ItemGroup>


    <ItemGroup>
        <Compile Include="..\..\src\CADShared\Basal\CLS\*.cs" Link="CLS\%(Filename)%(Extension)" />
        <Compile Include="..\..\src\CADShared\Basal\DataStructures\*.cs" Link="DataStructures\%(Filename)%(Extension)" />
        <Compile Include="..\..\src\CADShared\Basal\Cache\*.cs" Link="Cache\%(Filename)%(Extension)" />
        <Compile Remove="..\..\src\CADShared\PE\1AcadPeInfo.cs" />
        <Compile Remove="..\..\src\CADShared\PE\2PostCmd.cs" />
        <Compile Remove="..\..\src\CADShared\PE\DBmod.cs" />
        <Compile Include="..\..\src\CADShared\ExtensionMethod\json\MyJson.cs" Link="json\%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="DataStructures\" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="CLS\" />
    </ItemGroup>
    
</Project>