<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>

        <!--如果编译时候有大量的WPF错误,就隐藏NET35先,然后编译,然后打开,再编译-->
        <!--<TargetFrameworks>NET35;NET40;NET45</TargetFrameworks>-->
        
        <TargetFrameworks>NET40;NET45</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <PlatformTarget>x64</PlatformTarget>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'NET35'">
        <DefineConstants>$(Configuration);acad;ac2009</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'NET40'">
        <DefineConstants>$(Configuration);acad;ac2013</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'NET45'">
        <DefineConstants>$(Configuration);acad;ac2015</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <!--<ProjectReference Include="..\..\src\IFoxCAD.LoadForm\IFoxCAD.LoadEx.csproj" />-->
        <ProjectReference Include="..\..\src\IFoxCAD.AutoCad\IFoxCAD.AutoCad.csproj" />
        <ProjectReference Include="..\IFoxCAD.WPF\IFoxCAD.WPF.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="wpf\TestView.xaml.cs">
            <DependentUpon>TestView.xaml</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <Page Update="wpf\TestView.xaml">
            <SubType>Designer</SubType>
        </Page>
    </ItemGroup>

    <Import Project="..\TestShared\TestShared.projitems" Label="Shared" />
</Project>