<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>

        <OutputType>Exe</OutputType>
        <TargetFramework>NET45</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <Compile Include="..\..\src\CADShared\Basal\CLS\Index.cs" Link="CLS\Index.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\Range.cs" Link="CLS\Range.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\RuntimeHelpers.cs" Link="CLS\RuntimeHelpers.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\TupleElementNamesAttribute.cs" Link="CLS\TupleElementNamesAttribute.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\ValueTuple.cs" Link="CLS\ValueTuple.cs" />
      <Compile Include="..\..\src\CADShared\Basal\General\LoopState.cs" Link="LoopState.cs" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="CLS\" />
    </ItemGroup>

</Project>
