<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <OutputType>Exe</OutputType>
        <TargetFramework>NET45</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\..\src\CADShared\Basal\CLS\*.cs" Link="CLS\%(Filename)%(Extension)" />
        <Compile Include="..\..\src\CADShared\Basal\DataStructures\*.cs" Link="DataStructures\%(Filename)%(Extension)" />
        <Compile Include="..\..\src\CADShared\Basal\Cache\*.cs" Link="Cache\%(Filename)%(Extension)" />
        <Compile Include="..\..\src\CADShared\ExtensionMethod\json\MyJson.cs" Link="json\%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="DataStructures\" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="CLS\" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="json\" />
    </ItemGroup>

</Project>
