<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <OutputType>Exe</OutputType>
        <TargetFramework>NET45</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <Compile Include="..\..\src\CADShared\Basal\CLS\AsParallel.cs" Link="CLS\AsParallel.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\AssemblyExtensions.cs" Link="CLS\AssemblyExtensions.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\Index.cs" Link="CLS\Index.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\Range.cs" Link="CLS\Range.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\RuntimeHelpers.cs" Link="CLS\RuntimeHelpers.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\TupleElementNamesAttribute.cs" Link="CLS\TupleElementNamesAttribute.cs" />
      <Compile Include="..\..\src\CADShared\Basal\CLS\ValueTuple.cs" Link="CLS\ValueTuple.cs" />
      <Compile Include="..\..\src\CADShared\Basal\DataStructures\ConcurrentDictionary.cs" Link="DataStructures\ConcurrentDictionary.cs" />
      <Compile Include="..\..\src\CADShared\Basal\DataStructures\ConcurrentSet.cs" Link="DataStructures\ConcurrentSet.cs" />
      <Compile Include="..\..\src\CADShared\Basal\DataStructures\HashSet.cs" Link="DataStructures\HashSet.cs" />
      <Compile Include="..\..\src\CADShared\Basal\DataStructures\LinkedHashMap.cs" Link="DataStructures\LinkedHashMap.cs" />
      <Compile Include="..\..\src\CADShared\Basal\DataStructures\LinkedHashSet.cs" Link="DataStructures\LinkedHashSet.cs" />
      <Compile Include="..\..\src\CADShared\Basal\DataStructures\ListEx.cs" Link="DataStructures\ListEx.cs" />
      <Compile Include="..\..\src\CADShared\Basal\DataStructures\LoopList.cs" Link="DataStructures\LoopList.cs" />
      <Compile Include="..\..\src\CADShared\Basal\DataStructures\LoopState.cs" Link="DataStructures\LoopState.cs" />
    </ItemGroup>

    
    <ItemGroup>
      <Folder Include="DataStructures\" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="CLS\" />
    </ItemGroup>

</Project>
