<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <UseWindowsForms>false</UseWindowsForms>
        <UseWpf>false</UseWpf>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>IFoxFunKit</PackageId>
        <Title>IFoxFunKit</Title>
        <Product>IFoxFunKit</Product>
        <Company>InspireFunction</Company>
        <Authors>liuqihong</Authors>
        <Copyright>InspireFunction</Copyright>
        <Description>函数式编程类型库，提供Option&lt;T&gt;和Result&lt;T&gt;类型。</Description>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageProjectUrl>https://gitee.com/inspirefunction/ifoxcad</PackageProjectUrl>
        <RepositoryUrl>https://gitee.com/inspirefunction/ifoxcad.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>IFoxFunKit;Functional;Option;Result;Rust;FSharp</PackageTags>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugType>portable</DebugType>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\readme.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <!-- netstandard2.0需要额外的兼容性包 -->
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.1" />
    </ItemGroup>

</Project>
