<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>NET48</TargetFrameworks>
        <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>IFox.CAD.ACAD</PackageId>
        <Title>IFox.CAD.ACAD</Title>
        <Product>IFox.CAD.ACAD</Product>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugType>none</DebugType>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup>
        <DocumentationFile>bin\$(Configuration)\IFoxCAD.AutoCad.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'NET48'">
        <DefineConstants>$(Configuration);gcad</DefineConstants>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'NET48'">
        <PackageReference Include="GrxCAD.Net.2022" Version="1.0.0"  ExcludeAssets="runtime" />
        <Reference Include="Microsoft.CSharp" />
    </ItemGroup>


    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\..\readme.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>


    <!--<ItemGroup>
      <PackageReference Include="IndexRange" Version="1.0.2" />
    </ItemGroup>-->

    <Import Project="..\CADShared\CADShared.projitems" Label="Shared" />

    <!--确保分析器项目先编译，并引用分析器DLL-->
    <ItemGroup>
        <ProjectReference Include="..\FunKit\IFoxFunKit.Analyzers\IFoxFunKit.Analyzers.csproj" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" SetTargetFramework="TargetFramework=netstandard2.0" />
        <Analyzer Include="..\bin\$(Configuration)\netstandard2.0\IFoxFunKit.Analyzers.dll" />
    </ItemGroup>
</Project>
