<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>NET48</TargetFrameworks>
        <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <!--nuget package-->
    <PropertyGroup>
        <PackageId>IFox.CAD.ZCAD</PackageId>
        <Title>IFox.CAD.ZCAD</Title>
        <Product>IFox.CAD.ZCAD</Product>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugType>none</DebugType>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup>
        <DocumentationFile>bin\$(Configuration)\IFoxCAD.ZwCad.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <DefineConstants>$(Configuration);zcad;z2025</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ZWCAD.NetApi" Version="20.25.0" ExcludeAssets="runtime" />
        <PackageReference Include="PolySharp" Version="1.15.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <!--        <PackageReference Include="ZWCAD.NetApi" Version="20.25.0" ExcludeAssets="runtime"/>-->
        <Reference Include="Microsoft.CSharp" />
    </ItemGroup>

    <!-- 确保 IFoxFunKit 先编译 -->
    <Target Name="BuildIFoxFunKitFirst" BeforeTargets="BeforeBuild">
        <MSBuild Projects="$(RepoRoot)src\IFoxFunKit\IFoxFunKit.csproj"
                 Properties="Configuration=$(Configuration);TargetFramework=netstandard2.0" />
    </Target>
</Project>
