<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>NET35</TargetFrameworks>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <PlatformTarget>x86</PlatformTarget>
        <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>IFox.CAD.ACAD</PackageId>
        <Title>IFox.CAD.ACAD</Title>
        <Product>IFox.CAD.ACAD</Product>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
        <DebugType>full</DebugType>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
        <DebugType>none</DebugType>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup>
        <DocumentationFile>bin\$(Configuration)\IFoxCAD.Acad08.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'NET35'">
        <DefineConstants>$(Configuration);acad;ac2008;ac2009</DefineConstants>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'NET35'">
        <PackageReference Include="JJBox.Acad2008" Version="1.0.0" ExcludeAssets="runtime" />
        <!--<PackageReference Include="Autocad.NetApi" Version="17.2.0"  ExcludeAssets="runtime"/>-->
    </ItemGroup>

    <!-- IFoxFunKit 源文件链接 -->
    <ItemGroup>
        <Compile Include="..\FunKit\IFoxFunKit\*.cs" Link="IFoxFunKit\*.cs" />
        <Analyzer Include="..\bin\$(Configuration)\netstandard2.0\IFoxFunKit.Analyzers.dll" />
    </ItemGroup>

    <!--确保分析器项目先编译-->
    <ItemGroup>
        <ProjectReference Include="..\FunKit\IFoxFunKit.Analyzers\IFoxFunKit.Analyzers.csproj" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" SetTargetFramework="TargetFramework=netstandard2.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\..\readme.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <!--<ItemGroup>
      <PackageReference Include="IndexRange" Version="1.0.2" />
    </ItemGroup>-->

    <Import Project="..\CADShared\CADShared.projitems" Label="Shared" />

    <ItemGroup>
        <Compile Include="..\IFoxCAD.AutoCad\GlobalUsings.cs" Link="\%(FileName)%(Extension)" />
    </ItemGroup>


</Project>