<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>NET35</TargetFrameworks>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <PlatformTarget>x86</PlatformTarget>
        <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
        <BuildInParallel>false</BuildInParallel>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>IFox.CAD.ACAD2008</PackageId>
        <Title>IFox.CAD.ACAD2008</Title>
        <Product>IFox.CAD.ACAD2008</Product>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
        <DebugType>full</DebugType>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
        <DebugType>none</DebugType>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup>
        <DocumentationFile>bin\$(Configuration)\IFoxCAD.Acad08.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'NET35'">
        <DefineConstants>$(Configuration);acad;ac2008;ac2009</DefineConstants>
    </PropertyGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'NET35'">
        <PackageReference Include="JJBox.Acad2008" Version="1.0.0" ExcludeAssets="runtime" />
        <!--<PackageReference Include="Autocad.NetApi" Version="17.2.0"  ExcludeAssets="runtime"/>-->
    </ItemGroup>

    <!-- 确保 IFoxFunKit 先编译 -->
    <Target Name="BuildIFoxFunKitFirst" BeforeTargets="BeforeBuild">
        <MSBuild Projects="$(RepoRoot)src\IFoxFunKit\IFoxFunKit.csproj"
                 Properties="Configuration=$(Configuration);TargetFramework=netstandard2.0" />
    </Target>

    <!--<ItemGroup>
      <PackageReference Include="IndexRange" Version="1.0.2" />
    </ItemGroup>-->

    <ItemGroup>
        <Compile Include="$(RepoRoot)src\IFoxCAD.AutoCad\GlobalUsings.cs" Link="\%(FileName)%(Extension)" />
    </ItemGroup>

</Project>