<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>NET35</TargetFrameworks>
        <PlatformTarget>x86</PlatformTarget>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <PropertyGroup>
        <PackageId>IFox.CAD.ACAD</PackageId>
        <Title>IFox.CAD.ACAD</Title>
        <Product>IFox.CAD.ACAD</Product>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugType>none</DebugType>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <DocumentationFile>bin\Release\IFoxCAD.AutoCad.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'NET35'">
        <DefineConstants>$(Configuration);acad;ac2008;ac2009</DefineConstants>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'NET35'">
        <PackageReference Include="JJBox.Acad2008" Version="1.0.0" ExcludeAssets="runtime" />
        <!--<PackageReference Include="Autocad.NetApi" Version="17.2.0"  ExcludeAssets="runtime"/>-->
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\..\readme.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <!--<ItemGroup>
      <PackageReference Include="IndexRange" Version="1.0.2" />
    </ItemGroup>-->

    <Import Project="..\CADShared\CADShared.projitems" Label="Shared" />

    <ItemGroup>
        <Compile Include="..\IFoxCAD.AutoCad\GlobalUsings.cs" Link="\%(FileName)%(Extension)" />
    </ItemGroup>
</Project>
