<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net35</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>        
        <OutputType>Exe</OutputType>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <IsPackable>false</IsPackable>        
        <NoWarn>CS1591;CS8618;CS8625;CS8601;CS8603</NoWarn>
    </PropertyGroup>

    <!--添加语法分析器-->
    <ItemGroup>
        <Analyzer Include="..\..\bin\$(Configuration)\netstandard2.0\IFoxFunKit.Analyzers.dll" />
    </ItemGroup>

    <!--确保分析器项目先编译-->
    <ItemGroup>
        <ProjectReference Include="..\IFoxFunKit.Analyzers\IFoxFunKit.Analyzers.csproj" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" SetTargetFramework="TargetFramework=netstandard2.0" />
    </ItemGroup>


    <!-- 文件链接：引入Option和Result类型定义，用于反射读取MustHandleMember特性 -->
    <ItemGroup>
        <Compile Include="..\IFoxFunKit\src\**\*.cs" Link="IFoxFunKit\src\%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>
</Project>
