<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<PlatformTarget>x64</PlatformTarget>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<AssemblyVersion>1.0.0.*</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<Deterministic>false</Deterministic>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>full</DebugType>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'NET48'">
		<DefineConstants>$(Configuration);acad;a2024</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
		<DefineConstants>$(Configuration);acad;a2025</DefineConstants>
		<EnableDynamicLoading>true</EnableDynamicLoading>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'NET48'">
		<PackageReference Include="AutoCAD.NET" Version="20.0.0" ExcludeAssets="runtime">
		</PackageReference>

		<PackageReference Include="System.Text.Json" Version="9.0.0"/>
		
		<Reference Include="Microsoft.CSharp"/>
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
		<PackageReference Include="AutoCAD.NET" Version="25.0.1" ExcludeAssets="runtime"/>
	</ItemGroup>
	
	<ItemGroup>
	  	<ProjectReference Include="..\..\src\IFoxCAD.AutoCad\IFoxCAD.AutoCad.csproj" />
	</ItemGroup>
	<Import Project="..\TestShared\TestShared.projitems" Label="Shared" />
</Project>