<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <OutputType>Exe</OutputType>
        <TargetFramework>net35</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>

        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>

        <ImplicitUsings>disable</ImplicitUsings>
        <PlatformTarget>x86</PlatformTarget>
        <RepoRoot>$(MSBuildThisFileDirectory)..\..\..\</RepoRoot>

    </PropertyGroup>

    <ItemGroup>
        <Compile Include="$(RepoRoot)src\CADShared\PE\PeInfo.cs" Link="PE\PeInfo.cs" />
        <Compile Include="$(RepoRoot)src\CADShared\PE\StringHelper.cs" Link="PE\StringHelper.cs" />
        <Compile Include="$(RepoRoot)src\CADShared\PE\DllImportGenerator.cs" Link="PE\DllImportGenerator.cs" />
        <Compile Include="$(RepoRoot)src\CADShared\PE\CppMangledNameParser.cs" Link="PE\CppMangledNameParser.cs" />
        <Compile Include="$(RepoRoot)src\CADShared\PE\CppToCSharpMapper.cs" Link="PE\CppToCSharpMapper.cs" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="PE\" />
    </ItemGroup>

</Project>