version: '1.0'
name: push-nuget
displayName: push-nuget
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - v0.9
    tags:
      prefix:
        - v
stages:
  - name: stage-70e47d31
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@dotnet
        name: build_dotnet
        displayName: .NET Core 构建
        dotnetVersion: '8.0'
        commands:
          - '# input your command here'
          - mkdir out
          - dotnet restore
          - dotnet build --configuration Release -o out
          - dotnet pack --configuration Release -o ./out
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./out
        caches:
          - ~/.nuget/packages
        notify: []
        strategy:
          retry: '0'
  - name: stage-0f206cdc
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@dotnet
        name: nuget
        displayName: 上传
        dotnetVersion: '8.0'
        commands:
          - '# input your command here'
          - dotnet nuget push ./out/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./out
        caches:
          - ~/.nuget/packages
        notify: []
        strategy:
          retry: '0'
