<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>

        <TargetFrameworks>NET35</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <PlatformTarget>x86</PlatformTarget>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>

        <!-- 禁用资源生成，避免.NET Core MSBuild的ResGen错误 -->
        <GenerateResourceNeverGenerateTypeMetadata>true</GenerateResourceNeverGenerateTypeMetadata>
        <EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>

        <!-- RuntimeHelpers 的重复警告 -->
        <NoWarn>CS8012;CS1685</NoWarn>
        <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'NET35'">
        <DefineConstants>$(Configuration);acad;ac2008;ac2009</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <!--<ProjectReference Include="..\..\src\IFoxCAD.LoadForm\IFoxCAD.LoadEx.csproj" />-->
        <ProjectReference Include="..\..\src\IFoxCAD.Acad08\IFoxCAD.Acad08.csproj" />
    </ItemGroup>

    <Import Project="..\TestShared\TestShared.projitems" Label="Shared" />

    <ItemGroup>
        <Compile Include="..\TestAcad09plus\GlobalUsings.cs" Link="\%(FileName)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\TestAcad09plus\拦截输入法\**\*.cs" Exclude="..\TestAcad09plus\拦截输入法\**\*xaml*.cs">
            <Link>拦截输入法\%(RecursiveDir)%(FileName)%(Extension)</Link>
        </Compile>
    </ItemGroup>
</Project>
