<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net35</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <IsPackable>false</IsPackable>
        <NoWarn>CS1591;CS8618;CS8625;CS8601;CS8603</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <!-- net35 项目直接编译 IFoxFunKit 源代码 -->
        <Compile Include="$(RepoRoot)src\IFoxFunKit\src\Option\*.cs" Link="Option\%(Filename)%(Extension)" />
        <Compile Include="$(RepoRoot)src\IFoxFunKit\src\Nullable\*.cs" Link="Nullable\%(Filename)%(Extension)" />
    </ItemGroup>

</Project>
