<Project>
    <!--版本号和提示-->
    <PropertyGroup>
        <Version>0.9.9.1</Version>
        <PackageReleaseNotes>暂时屏蔽浩辰的打包，保留浩辰的项目</PackageReleaseNotes>
    </PropertyGroup>

    <!-- 定义根路径 -->
    <PropertyGroup>
        <!-- 获取项目文件的目录 -->
        <ProjectDir>$(MSBuildProjectDirectory)\</ProjectDir>
        <!-- 计算到根目录的路径 (src目录的上级) -->
        <RepoRoot>$([System.IO.Path]::GetFullPath('$(ProjectDir)..\..\'))</RepoRoot>
        <!-- 统一的输出目录 -->
        <OutputPath>$(RepoRoot)bin\$(Configuration)\</OutputPath>
        <!-- NuGet包输出路径 -->
        <PackageOutputPath>$(RepoRoot)bin\$(Configuration)\</PackageOutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <!--<PlatformTarget>x64</PlatformTarget>-->
        <RootNamespace>IFoxCAD.CAD</RootNamespace>
        <UseWindowsForms>true</UseWindowsForms>
        <UseWpf>true</UseWpf>
    </PropertyGroup>

    <PropertyGroup><!--nuget包信息-->
        <Company>InspireFunction</Company>
        <Authors>xsfhlzh;vicwjb;liuqihong;DYH</Authors>
        <Copyright>InspireFunction</Copyright>
        <Description>基于.NET的二次开发基本类库.</Description>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageProjectUrl>https://gitee.com/inspirefunction/ifoxcad</PackageProjectUrl>
        <RepositoryUrl>https://gitee.com/inspirefunction/ifoxcad.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>IFox;cad;AutoCad;C#;NET;ZwCad</PackageTags>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
    </PropertyGroup>

</Project>