<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>

        <TargetFrameworks>NET35;NET40;NET45</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <Version>0.4</Version>
        <Authors>xsfhlzh;vicwjb;liuqihong</Authors>
        <Company>InspireFunction</Company>
        <Description>WPF的简单MVVM模式开发类库</Description>
        <Copyright>InspireFunction</Copyright>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageProjectUrl>https://gitee.com/inspirefunction/ifoxcad</PackageProjectUrl>
        <RepositoryUrl>https://gitee.com/inspirefunction/ifoxcad.git</RepositoryUrl>
        <PackageTags>IFoxCAD;C#;NET;WPF;MVVM</PackageTags>
        <RepositoryType>git</RepositoryType>
        <PackageReleaseNotes>开启可空类型.</PackageReleaseNotes>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(TargetFramework)' == 'NET35'">
        <DefineConstants>$(Configuration);acad;ac2009</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'NET40'">
        <DefineConstants>$(Configuration);acad;ac2013</DefineConstants>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(TargetFramework)' == 'NET45'">
        <DefineConstants>$(Configuration);acad;ac2015</DefineConstants>
    </PropertyGroup>

    <!-- 条件包引用 -->
    <ItemGroup>
        <!-- .NET 4.5+ 使用 Microsoft.Xaml.Behaviors.Wpf -->
        <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.31" Condition="'$(TargetFramework)' == 'NET45'" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>
</Project>
