name: Publish NuGet Package

on:
  push:
    tags:
      - 'v0.7*' # 当推送以 v 开头的标签时触发，例如 v0.9

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./src/CAD/

      # 自动从 Tag 名称提取版本号并打包
      - name: Pack NuGet Package
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src\CAD\IFox.CAD.ACAD\IFox.CAD.ACAD.csproj
          NUGET_KEY: ${{ secrets.NUGET_AUTH_TOKEN }}
          NUGET_SOURCE: https://api.nuget.org/v3/index.json